version: '3'

services:
  adocaopets:
    image: tomsik68/xampp
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - C:/Users/usuario/Desktop/adocaoPets:/opt/lampp/htdocs
      - C:/Users/usuario/Desktop/adocaoPets/assets/bd/adocaopets.sql:/docker-entrypoint-initdb.d/adocaopets.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: adocaopets
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - adocaopets
